<?php

namespace App\Models;

use App\Collections\BaseCollection;
use Illuminate\Database\Eloquent\Model;

class Base extends Model
{
    //
    protected $primaryKey           =   'uuid';
    protected $keyType              =   'string';

    public $incrementing            =   false;
    public $timestamps              =   false;

    public function newCollection(array $models = [])
    {
        return new BaseCollection($models);

        // return parent::newCollection($models); // TODO: Change the autogenerated stub
    }
}
