<?php

namespace App\Models\RBAC;

use App\Models\Base as BaseModel;
use App\Scopes\StatusScope;

class Base extends BaseModel
{
    //
    protected $connection           =   'rbac';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // rbac下注册全局查询范围
        static::addGlobalScope( new StatusScope() );
    }
}
